
-- CONHECENDO TABELA DE PAISES 

 SELECT * FROM PAIS

--CONHECENDO A TABELA DE ESTADOS

 SELECT * FROM ESTADOS WHERE COD_PAIS = 2

-- CONHECENDO A TABELA DE ALUNOS

 SELECT * FROM ALUNOS 

-- FILTRO DE TABELAS (WHERE)

 SELECT * FROM ALUNOS WHERE IDADE >= 30
 SELECT * FROM ALUNOS WHERE SEXO = 'M' AND IDADE >= 30
 SELECT * FROM ALUNOS WHERE SEXO = 'M' OR IDADE >= 30

 -- MOSTRE TODAS AS CIDADE DE MINAS GERAIS 

 SELECT * FROM CIDADES WHERE UF = 'MG'

 -- MOSTRE AS INFORMAÇOES  MAS TRAGA SOMENTE AS SEGUINTES COLUNAS : CPF, NOME, IDADE
 --TRAZENDO COLUNA ESPECIFICAS
SELECT CPF, NOME, IDADE FROM ALUNOS 

SELECT NOME, IDADE FROM ALUNOS ORDER BY NOME -- ORDEM PADRÃO 
SELECT NOME, IDADE FROM ALUNOS ORDER BY NOME DESC -- DECRECENTE

--MOSTRE TODOS OS CURSOS E TODAS SUAS COLUNAS MAS ORDEANDO POR NOME DO CURSO
SELECT * FROM CURSOS ORDER BY NOME