# -*- coding: utf-8 -*-
"""rev_python_25n3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Fy-2WCjAPLJXc89FDL5BUOnWBglDeez
"""

print("hello world")

#25/09/2025
#revisão da linguagem python para análise de dados

#crie 3 varieave para que voce se apresente
#atribua valores na variaveis e os exiba na tela
#me chamo 'fulano, sou'função' e moro em 'cidade'

nome = "matheus"
profissão = "motorista reprovado"
cidade = "Rio Preto"

print ("Me chamo" , nome , "sou" , profissão, "e moro em" ,cidade)
#uso do format
print(f"Me chamo {nome} sou {profissão} e moro em {cidade}")

## crie um programa que receba a idade de uma pessoa emostre em tela se ela é maio ou menor de idade
idade = int

idade = int(input("Qual a sua idade?"))

if idade >= 18 :
    print(f"sua idade é {idade} voce é maior de idade")
else:
    print(f"sua idade é {idade} voce é menor de idade")

#crie um programa que receba dosi nome e duas alturas.
#mostre em tela a mais alta ou se possuem a mesma altura

nome1 = input("Digite o nome da 1º pessoa")
altura1 = float(input(f"digite a altura do(a) {nome1}"))

nome2 = input("Digite o nome da 2º pessoa")
altura2 = float(input(f"digite a altura do(a) {nome2}"))

if altura1 > altura2 :
    print(f"{nome1} é mais alta que {nome2}")
elif altura2 > altura1:
    print(f"{nome2} é mais alta que {nome1}")
else:
    print(f"{nome1} e {nome2} tem a mesma altura {altura1}")

#crie u programa que receba o salario e a idade de uma pessoa
# se a idade for maior ou igual a 50 e o salario menor que 3500 reajuste o salario em 7.5%
#senão reajuste em 5%
#mostre o salario reajustado e a diferença bruta de reajuste


idade = int (input("qual a sua idade"))
salario = float( input("qual o seu salario atual"))
#
if idade >= 50 and salario < 3500 :
    tx = 7.5
    salarioReajustado = salario * 1.075
else :
    tx = 5
    salarioReajustado = salario * 1.05
#
print(f"Novo salário: R${salarioReajustado} | Taxa de {tx}")
print(f"Diferença bruta : R${salarioReajustado - salario}")

#crie um programa que verifica se uma pessoa pode ou não doar sangue.
#sera digitada a idade e o peso da pessoa
#regra: somente pessoas com idade entre 16 e 69 anos e peso a partir de 50g
#podem doar

idade = int (input("qual a sua idade? "))
peso = float (input("qual seu peso? "))
#
if (idade < 16 or idade > 69 or peso <= 50) :
    print("voce não pode doar sangue")
else :
    print ("voce pode doar sangue")

