-- aula perdida

--18/02/2025
--EXPLORANDO BANCO DE DADOS VENDAS

SELECT * FROM Customers

--FORNECEDORES
SELECT * FROM Suppliers

-- PEDIDOS DE VENDA
SELECT * FROM Orders

-- MOSTRE TODOS OS PRODUTOS JA VENDIDOS PARA O BRAZIL
-- COLUNAS : CODIGO DO PRODUTO, NOME DO PRODUTO,
-- ORDERNE POR NOME DO PRODUTO

-- O COMANDO DISTINCT NÃO TRARA LINHAS DUPLICADAS
SELECT DISTINCT PROD.ProductID AS CODIGO, PROD.ProductName AS PRODUTO
FROM Products PROD
INNER JOIN [Order Details] OD ON OD.ProductID = PROD.ProductID
INNER JOIN Orders P ON  P.OrderID = OD.OrderID
WHERE 
     P.ShipCountry = 'BRAZIL'
ORDER BY PRODUTO

-- MOSTRE A QUANTIDADE VENDIDA, POR PRODUTO, DE TODOS OS PRODUTOS ENVIADOS 
-- PARA O BRAZIL

SELECT PROD.ProductID AS CODIGO,
       PROD.ProductName AS PRODUTO,
       SUM (OD.Quantity) AS QTD
FROM Products PROD
INNER JOIN [Order Details] OD ON OD.ProductID = PROD.ProductID
INNER JOIN Orders P ON  P.OrderID = OD.OrderID
WHERE 
     P.ShipCountry = 'BRAZIL'
     GROUP BY PROD.ProductID,
     PROD.ProductName
ORDER BY PRODUTO

--GROUP BY TEM QUE USAR OS PRIMEIROS CAMPOS QUE ESTAO NO SELECT

-- MOSTRE A QUANTIDADE DE PRODUTOS FORNECIDA POR FORNECEDOR
-- COLUNAS: CÓDIGO DO PRODUTO, NOME DO PRODUTO, NOME DO FORNECEDOR, QUANTIDADE VENDIDA
-- EX: 001 | QUEIJO MINAS | LATICINIOS SENAI | 1200

SELECT PROD.ProductID CODIGO,
  PROD.ProductName AS NOME_PRODUTO,
  FORNEC.CompanyName, SUM (OD.Quantity) AS QTD_VENDIDA
FROM Products PROD
INNER JOIN Suppliers FORNEC ON FORNEC.SupplierID = PROD.SupplierID
INNER JOIN [Order Details] OD ON OD.ProductID = PROD.ProductID
GROUP BY PROD.ProductID,
         PROD.ProductName,
         FORNEC.CompanyName
ORDER BY FORNEC.CompanyName

-- CRIE UMA CONSULTA QUE MOSTRE AS VENDAS GERAIS POR PAÍS
-- COLUNAS :  DATA DA VENDA,PEDIDO, VENDEDOR, CLIENTE, CIDADE, REGIAO, PAÍS,
-- VALOR TOTAL DA VENDA

SELECT O.OrderDate AS DATA_VENDA, O.OrderID AS PEDIDO,
CONCAT(F.FirstName, '', F.LastName) AS VENDEDOR,
O.ShipName AS CLIENTE, 
O.ShipCity AS CIDADE,
ISNULL ( O.ShipRegion, 'N/A') AS REGIAO,
O.ShipCountry PAIS,
ROUND(SUM((OD.Quantity * OD.UnitPrice) * (1 - OD.Discount)), 2) AS TOTAL_VENDA
FROM Orders O
INNER JOIN Employees F ON F.EmployeeID = O.EmployeeID
INNER JOIN [Order Details] OD ON OD.OrderID = O.OrderID
GROUP BY O.OrderDate,O.OrderID,CONCAT(F.FirstName, '', F.LastName),
O.ShipName,
O.ShipCity,
ISNULL ( O.ShipRegion, 'N/A'),
O.ShipCountry
ORDER BY TOTAL_VENDA

-- CONCAT AGRUPA COLUNAS 
-- ISNULL TROCA O VALOR DO CAMPO QUE ESTA VAZIO OU COALESCE

-- MOSTRE O TOTAL VENDIDO PARA CADA CIDADE
-- COLUNAS: NOME DA CIDADE, NOME DO PAÍS, TOTAL VENDIDO
--EX: SAO PAULO | BRASIL | 150000

SELECT O.ShipCity AS CIDADE,
O.ShipCountry AS PAÍS,
ROUND(SUM((OD.Quantity * OD.UnitPrice) * (1 - OD.Discount)),2) AS TOTAL_VENDA
FROM Orders O
INNER JOIN [Order Details] OD ON OD.OrderID = O.OrderID
    GROUP BY 
O.ShipCity,O.ShipCountry
    ORDER BY 
TOTAL_VENDA DESC

