--1
SELECT *
FROM ESTADOS
ORDER BY ESTADOS.NOME

--2
SELECT *
FROM PAIS
WHERE PAIS.NOME LIKE '%A'

--3
SELECT *
FROM MATRICULA
WHERE COD_CURSO != '4'

--4 
SELECT *
FROM ALUNOS
WHERE IDADE >= 20 AND IDADE <=30 AND SEXO = 'F'

--5
SELECT AREA.NOME AS AREA, CURSOS.NOME AS CURSO, ALUNOS.NOME AS ALUNO 
FROM ALUNOS
INNER JOIN MATRICULA ON MATRICULA.CPF = ALUNOS.CPF  
INNER JOIN CURSOS ON CURSOS.COD_CURSO = MATRICULA.COD_CURSO
INNER JOIN AREA ON AREA.COD_AREA = CURSOS.COD_AREA
ORDER BY CURSO
