--1
SELECT CURSOS.NOME AS AREA, SUM (MATRICULA.VALOR) AS FATURAMENTO
FROM MATRICULA
INNER JOIN CURSOS ON CURSOS.COD_CURSO = MATRICULA.COD_CURSO
GROUP BY CURSOS.NOME

--2
SELECT ALUNOS.SEXO, COUNT(*) AS QTD_ALUNO
FROM ALUNOS
GROUP BY ALUNOS.SEXO

--3
SELECT ALUNOS.NOME AS ALUNO, CIDADES.NOME AS CIDADE, ESTADOS.UF AS ESTADO, MATRICULA.VALOR AS MATRICULA 
FROM ALUNOS
INNER JOIN MATRICULA ON MATRICULA.CPF = ALUNOS.CPF
INNER JOIN CIDADES   ON CIDADES.COD_CIDADE = ALUNOS.COD_CIDADE
INNER JOIN ESTADOS   ON CIDADES.UF = ESTADOS.UF
WHERE ESTADOS.UF!='MG'
ORDER BY MATRICULA.VALOR DESC